[package]
name = "brainfuck"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.2"
either = "1.8.0"
clap = { version = "4.0.0", features = ["derive", "unicode"] }
