name: Compile and save program

on:
  push:
    branches: [main]
    paths-ignore: ["samples/**", "**.md"]
  workflow_dispatch:
    
jobs:    
  build:
    strategy:
      fail-fast: false
      matrix:
        target: 
          - {target: aarch64-unknown-linux-gnu, platform: ubuntu-latest, cross: true}
          - {target: i686-pc-windows-gnu, platform: ubuntu-latest, cross: true}
          - {target: i686-unknown-linux-gnu, platform: ubuntu-latest, cross: true}
          - {target: x86_64-apple-darwin, platform: macos-latest, cross: false}
          - {target: x86_64-pc-windows-gnu, platform: ubuntu-latest, cross: true}
          - {target: x86_64-unknown-linux-gnu, platform: ubuntu-latest, cross: false}
          
    name: Build executable
    runs-on: ${{ matrix.target.platform }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.target.cross }}
          command: build
          args: --target ${{ matrix.target.target }} --release --all-features --target-dir=/tmp
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target.target }}
          path: |
            /tmp/${{ matrix.target.target }}release/brainfuck*
            !**/*.d
            !**/*.pdb
