name: Compile and save program

on:
  push:
    branches: [main]
    paths-ignore: ["samples/**", "**.md"]
  workflow_dispatch:
    
jobs:    
  build:
    strategy:
      fail-fast: false
      matrix:
        target: 
          - aarch64-unknown-linux-gnu
          - i686-pc-windows-gnu
          - i686-unknown-linux-gnu
          #- x86_64-apple-darwin # fails
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          
    name: Build executable
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: |
          rustup target add ${{ matrix.target }}
          sudo apt-get install gcc-multilib
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --release --all-features --target-dir=/tmp
      - name: Debug missing files
        run: |
          echo "root dir:"
          ls /home/runner/work/brainfuck/brainfuck
          echo "target dir:"
          ls /tmp/release
          echo "deps:"
          ls /tmp/release/deps
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            /tmp/release
          #/tmp/release/brainfuck*
          #!**/*.d
          #!**/*.pdb
