name: Compile and save program

on:
  push:
    branches: [main]
    paths-ignore: ["samples/**", "**.md"]
    
jobs:    
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-unknown-linux-gnu, i686-pc-windows-gnu, i686-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu]
        
    name: Build executable
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: |
          rustup target add ${{ matrix.target }}
          sudo apt-get install gcc-multilib gcc-aarch64-linux-gnu
      - name: Build
        uses: shogan/rust-musl-action@v1.0.2
        with:
          args: cargo build --target ${{ matrix.target }} --release --all-features
      - name: Debug missing files
        run: |
          ls target/release
          ls /home/runner/work/brainfuck/brainfuck
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            target/release/brainfuck*
            !**/*.d
            !**/*.pdb
